accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [
    url(r'^entrar/$', login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^registro/$', views.register, name='register'),
]

appfabio1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='account')),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^sobre/$', views.about, name='about'),
    url(r'^jogos/$', views.games, name='games'),
    url(r'^ranking/$', views.ranking, name='ranking'),
    url(r'^historico/$', views.history, name='history'),
    url(r'^time/$', views.team, name='team'),
    url(r'^painel/$', views.panelhome, name='panelhome'),
]

games/urls.py
from django.conf.urls import url


urlpatterns = [
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Team(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=100, unique=True)
    backgroud = models.CharField('Fundo', max_length=100)
    front = models.CharField('Frente', max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Time'
        verbose_name_plural = 'Times'


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    ra = models.CharField('RA', max_length=100)
    classroom = models.CharField('Sala de Aula', max_length=100)

core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

games/models.py
# encoding=utf-8

from __future__ import unicode_literals

from django.db import models


class Sport(models.Model):
    name = models.CharField('Nome', max_length=100)
    duration_time = models.DecimalField('Duração geral (min)', max_digits=10, decimal_places=0)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Esporte'
        verbose_name_plural = 'Esportes'


class Game(models.Model):
    name = models.CharField('Nome', max_length=100)
    sport = models.ForeignKey(Sport, on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('Em Breve', 'Em Breve'),
        ('Em Andamento', 'Em Andamento'),
        ('Terminado', 'Terminado'),
    )
    status = models.CharField('Status', default='Em Breve', choices=STATUS_CHOICES, max_length=100)
    start = models.DateTimeField('Começa em', null=True)
    score_red = models.DecimalField('Pontos Time Vermelho', max_digits=10, decimal_places=0, null=True)
    score_blue = models.DecimalField('Pontos Time Azul', max_digits=10, decimal_places=0, null=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Jogo'
        verbose_name_plural = 'Jogos'

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy


User = get_user_model()

class RegisterView(CreateView):
    form_class = UserCreationForm
    model = User
    template_name = 'account/register.html'
    success_url = reverse_lazy('account.login')


register = RegisterView.as_view()

core/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic

from games.models import Game


class HomeView(generic.TemplateView):
    template_name = 'pages/home.html'


class AboutView(generic.TemplateView):
    template_name = 'pages/about.html'


class GamesView(LoginRequiredMixin, generic.ListView):
    model = Game
    context_object_name = 'games'
    template_name = 'pages/games.html'


class RankingView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'pages/ranking.html'


class HistoryView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'pages/history.html'


class TeamView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'pages/team.html'


class PanelHomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'panel/home.html'


home = HomeView.as_view()
about = AboutView.as_view()
games = GamesView.as_view()
ranking = RankingView.as_view()
history = HistoryView.as_view()
team = TeamView.as_view()
panelhome = PanelHomeView.as_view()

games/views.py
from django.shortcuts import render

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'core:home' %}">App Fabio 1</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'core:home' %}">Inicio</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'core:games' %}">Jogos</a></li>
                    <li><a href="{% url 'core:ranking' %}">Ranking</a></li>
                    <li><a href="{% url 'core:history' %}">Histórico</a></li>
                    <li><a href="{% url 'core:team' %}">Time</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Conta <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'core:panelhome' %}">Paine de controle</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'account:logout' %}">Sair</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:login' %}">Entrar</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

{% block content %}

{% endblock %}

<script src="{% static 'assets/js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/base_panel.html
{% extends "base.html" %}

{% block title %}
    Painel | AppFabio1
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="active"><a href="#">Home</a></li>
                            <li><hr></li>
                            <li><a href="#">Profile</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% block panel %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/about.html
{% extends "base.html" %}

{% block title %}
    About | AppFabio1
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if perms.games %}
                            permitido
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/games.html
{% extends "base.html" %}

{% block title %}
    Games | AppFabio1
{% endblock %}

{% block content %}
    <div class="container">
        {% if perms.games %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Administração
                    </div>
                    <div class="panel-body">
                        <div class="container.fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <a href="#" class="btn btn-primary">Adicionar Esporte</a> | <a href="#" class="btn btn-primary">Adicionar Jogo</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Em Andamento
                    </div>
                    <div class="panel-body">
                        <div class="container-fluid">
                            {% for game in games %}
                                {% if game.status == 'Em Andamento' %}
                                    <div class="row">
                                        <div class="col-md-12">
                                            <h2>{{ game.name }}</h2>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-3 col-md-offset-3 col-xs-3 col-xs-offset-3" align="center">
                                            <span style="font-size: 70px; color: red;">{{ game.score_red }}</span>
                                        </div>
                                        <div class="col-md-3 col-xs-3" align="center">
                                            <span style="font-size: 70px; color: blue;">{{ game.score_blue }}</span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <h4>Começou dia - {{ game.start }}</h4>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Em Breve
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover ">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Esporte</th>
                                    <th>Começa em</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for game in games %}
                                    {% if game.status == 'Em Breve' %}
                                        <tr>
                                            <td>{{ game.name }}</td>
                                            <td>{{ game.sport }}</td>
                                            <td>{{ game.start }}</td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Terminado
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-hover ">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Esporte</th>
                                    <th>Começou em</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for game in games %}
                                    {% if game.status == 'Terminado' %}
                                        <tr>
                                            <td>{{ game.name }}</td>
                                            <td>{{ game.sport }}</td>
                                            <td>{{ game.start }}</td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/history.html
{% extends "base.html" %}

{% block title %}
    History | AppFabio1
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>Page History</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto aspernatur assumenda delectus eveniet exercitationem ipsa maxime molestiae mollitia natus nulla odio possimus praesentium quaerat rerum sunt tempore ullam, voluptate voluptatum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/home.html
{% extends "base.html" %}

{% block title %}
    Home | AppFabio1
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>Page Home</h2>                        
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto aspernatur assumenda delectus eveniet exercitationem ipsa maxime molestiae mollitia natus nulla odio possimus praesentium quaerat rerum sunt tempore ullam, voluptate voluptatum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/ranking.html
{% extends "base.html" %}

{% block title %}
    Ranking | AppFabio1
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>Page Ranking</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto aspernatur assumenda delectus eveniet exercitationem ipsa maxime molestiae mollitia natus nulla odio possimus praesentium quaerat rerum sunt tempore ullam, voluptate voluptatum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/team.html
{% extends "base.html" %}

{% block title %}
    Team | AppFabio1
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>Page Team</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto aspernatur assumenda delectus eveniet exercitationem ipsa maxime molestiae mollitia natus nulla odio possimus praesentium quaerat rerum sunt tempore ullam, voluptate voluptatum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/panel/home.html
{% extends "base_panel.html" %}

{% block panel %}
    <h2>Test panel home</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
{% endblock %}